version: '3'

volumes:
    prometheus_data: {}

services:
    # cadvisor:
    #     image: gcr.io/google-containers/cadvisor:latest
    #     container_name: cadvisor
    #     volumes:
    #         - /:/rootfs:ro
    #         - /var/run:/var/run:rw
    #         - /sys:/sys:ro
    #         - /var/lib/docker/:/var/lib/docker:ro
    #     networks:
    #         - trdthien-network

    node-exporter:
      image: prom/node-exporter:latest
      container_name: node-exporter
      restart: unless-stopped
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
      command:
        - '--path.procfs=/host/proc'
        - '--path.rootfs=/rootfs'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      expose:
        - 9100
      networks:
        -  trdthien-network

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: unless-stopped
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.enable-lifecycle'
        depends_on:
            - node-exporter
        networks:
            - trdthien-network

    grafana:
        image: grafana/grafana
        ports:
            - 4000:3000
        expose:
            - 4000
        volumes:
            - ./data:/var/lib/grafana
        restart: always
        depends_on:
            - prometheus
        networks:
            - trdthien-network
        user: '472'
networks:
    trdthien-network:
        external:
            name: trdthien-network
